# Without this, the volumes wouldn't mount to the host directories.
version: '3'

services:
  mosquitto:
    build: .
    image: mosquitto_2.0.20
    container_name: mosquitto
    volumes:
      - ./certs:/mosquitto/certs
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    network_mode: "host"
    environment:
      - TZ=America/Detroit
